#pragma once 

#define DEFAULT_PROBE_GI
//#define LARGE_RANGE_PROBE_GI
//#define STUPIDLY_HIGH_RES_PROBE_GI

#define SKY_SHADOWMAP_COUNT 32

#define VOXEL_GRID_X 256
#define VOXEL_GRID_Y 128
#define VOXEL_GRID_Z 256
#define VOXEL_GRID_RES glm::vec3(256,128,256)

#define VOXEL_GRID_SIZE_X 32
#define VOXEL_GRID_SIZE_Y 16
#define VOXEL_GRID_SIZE_Z 32
#define VOXEL_GRID_SIZE glm::vec3(VOXEL_GRID_SIZE_X,VOXEL_GRID_SIZE_Y,VOXEL_GRID_SIZE_Z)


#ifdef DEFAULT_PROBE_GI

#define PROBE_GRID_X 48
#define PROBE_GRID_Y 24
#define PROBE_GRID_Z 48
#define PROBE_GRID_RES glm::vec3(PROBE_GRID_X,PROBE_GRID_Y,PROBE_GRID_Z)

#define PROBE_SIZE_X 24.0f
#define PROBE_SIZE_Y 12.0f
#define PROBE_SIZE_Z 24.0f
#define PROBE_GRID_SIZE glm::vec3(PROBE_SIZE_X, PROBE_SIZE_Y, PROBE_SIZE_Z)

#else
#ifdef LARGE_RANGE_PROBE_GI

#define PROBE_GRID_X 64
#define PROBE_GRID_Y 32
#define PROBE_GRID_Z 64
#define PROBE_GRID_RES glm::vec3(PROBE_GRID_X,PROBE_GRID_Y,PROBE_GRID_Z)

#define PROBE_SIZE_X 32.0f
#define PROBE_SIZE_Y 16.0f
#define PROBE_SIZE_Z 32.0f
#define PROBE_GRID_SIZE glm::vec3(PROBE_SIZE_X, PROBE_SIZE_Y, PROBE_SIZE_Z)


#else 

#define PROBE_GRID_X 128
#define PROBE_GRID_Y 64
#define PROBE_GRID_Z 128
#define PROBE_GRID_RES glm::vec3(PROBE_GRID_X,PROBE_GRID_Y,PROBE_GRID_Z)

#define PROBE_SIZE_X 32.0f
#define PROBE_SIZE_Y 16.0f
#define PROBE_SIZE_Z 32.0f
#define PROBE_GRID_SIZE glm::vec3(PROBE_SIZE_X, PROBE_SIZE_Y, PROBE_SIZE_Z)

#endif
#endif